In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv(r"..\DATA\health_data_synthetic.csv")

BINARY     = ['family_history_diabetes', 'family_history_heart', 'family_history_obesity']

CONTINUOUS = [
    'age',
    'bmi',
    'systolic_bp',
    'diastolic_bp',
    'stress_level'
]

CATEGORICAL = {
    'gender':   ['Male', 'Female', 'Other'],
    'smoking':  ['Never', 'Former', 'Current'],
    'drinking': ['Never', 'Occasional', 'Regular', 'Heavy'],
    'exercise': ['Sedentary', 'Light', 'Moderate', 'Intense'],
}

TARGETS = ['diabetes_risk', 'heart_risk', 'obesity_risk']

RISK_MAP = {'Low': 0, 'Medium': 1, 'High': 2}

scaler = StandardScaler()
X_cont = pd.DataFrame(
    scaler.fit_transform(df[CONTINUOUS]),
    columns=CONTINUOUS, index=df.index
)

cat_dfs = []
for col, categories in CATEGORICAL.items():
    for cat in categories:
        cat_dfs.append(pd.Series(
            (df[col] == cat).astype(int),
            name=f"{col}_{cat}", index=df.index
        ))
X_cat = pd.concat(cat_dfs, axis=1)

X_bin = df[BINARY].reset_index(drop=True)
X_cont = X_cont.reset_index(drop=True)
X_cat  = X_cat.reset_index(drop=True)

x = pd.concat([X_cont, X_cat, X_bin], axis=1)

y_raw = df[TARGETS].reset_index(drop=True)
y = y_raw.map(lambda v: RISK_MAP[v])

x_train , x_val_test , y_train , y_val_test = train_test_split(x,y, test_size = 0.3 , random_state=23 , stratify=y['heart_risk'])
x_val , x_test , y_val , y_test = train_test_split(x_val_test, y_val_test , test_size = 0.5 , random_state=23 , stratify=y_val_test['heart_risk'])

In [36]:
list(df.columns)

['age',
 'gender',
 'bmi',
 'systolic_bp',
 'diastolic_bp',
 'smoking',
 'drinking',
 'exercise',
 'stress_level',
 'family_history_diabetes',
 'family_history_heart',
 'family_history_obesity',
 'diabetes_risk',
 'heart_risk',
 'obesity_risk']

In [7]:
y_train

       diabetes_risk  heart_risk  obesity_risk
39820              2           2             1
25044              0           0             0
41986              0           1             0
5356               1           2             2
1280               1           1             2
...              ...         ...           ...
12897              1           0             0
6211               1           1             1
44261              0           0             0
26571              1           0             0
30694              0           1             0

[35000 rows x 3 columns]

In [14]:
y_db = y_train["diabetes_risk"].values

y_db.shape

(35000,)

In [34]:

x_test

,age,bmi,systolic_bp,diastolic_bp,stress_level,gender_Male,gender_Female,gender_Other,smoking_Never,smoking_Former,...,drinking_Occasional,drinking_Regular,drinking_Heavy,exercise_Sedentary,exercise_Light,exercise_Moderate,exercise_Intense,family_history_diabetes,family_history_heart,family_history_obesity
20184,-1.001160,-0.938696,0.291104,0.040725,-1.877845,0,1,0,1,0,...,1,0,0,0,0,0,1,0,0,1
16681,-0.652152,-1.788119,-1.352522,-1.460775,1.385039,1,0,0,1,0,...,1,0,0,1,0,0,0,0,0,0
49144,2.663420,-0.803561,-0.530709,-0.359675,-0.671025,0,1,0,1,0,...,1,0,0,1,0,0,0,1,1,0
9703,-0.215893,-0.822866,0.291104,0.541224,-0.313449,0,1,0,0,0,...,0,0,0,0,1,0,0,1,1,0
40015,0.918382,-0.340239,0.291104,-0.059375,0.982765,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29920,1.703649,-0.456069,0.814076,0.240925,-0.671025,0,1,0,1,0,...,0,1,0,0,1,0,0,0,0,0
16736,-0.913908,0.509184,-1.128391,-0.559875,-1.296784,0,1,0,1,0,...,1,0,0,0,1,0,0,0,1,0
7867,-0.913908,-0.610510,-1.651363,-1.560875,0.267613,0,1,0,1,0,...,0,1,0,0,1,0,0,0,0,0
11452,-0.652152,-1.170357,1.038207,0.341025,0.491098,0,1,0,1,0,...,1,0,0,1,0,0,0,0,1,0
24500,0.220367,-0.378849,-0.231868,0.641324,-0.358146,1,0,0,1,0,...,1,0,0,0,0,1,0,0,1,0

In [22]:
x_train.shape

(35000, 22)

In [16]:
from pathlib import Path

In [ ]:
def get_information():
    
    data = []

    age = int(input("ENTER YOUR AGE : "))
    data.append(age)
    gender = input("GENDER : Male , Female , Other")
    data.append(gender)
    bmi = float(input("ENTER YOUR BMI : "))
    data.append(bmi)
    s_bp = int(input("ENTER YOUR S BP : "))
    data.append(s_bp)
    d_bp = int(input("ENTER YOUR D BP : "))
    data.append(d_bp)
    smoking = input("Never, Former, Current")
    data.append(smoking)
    drinking = input("Never, Occasional, Regular, Heavy")
    data.append(drinking)
    exersize = input("Sedentary, Light, Moderate, Intense")
    data.append(exersize)
    stress_levels = int(input("ENTER YOUR STRESS : "))
    data.append(stress_levels)
    db_hist = int(input("ENTER 1 FOR TRUE ELSE 0"))
    data.append(db_hist)
    hd_hist = int(input("ENTER 1 FOR TRUE ELSE 0"))
    data.append(hd_hist)
    ob_hist = int(input("ENTER 1 FOR TRUE ELSE 0"))
    data.append(ob_hist)

    labels = [
    'age',
    'gender',
    'bmi',
    'systolic_bp',
    'diastolic_bp',
    'smoking',
    'drinking',
    'exercise',
    'stress_level',
    'family_history_diabetes',
    'family_history_heart',
    'family_history_obesity']
    
    f_data = []
    f_data.append(data)
   
    df = pd.DataFrame(f_data , columns=labels)

    return df

In [44]:
tp = get_information()

In [45]:
tp

,age,gender,bmi,systolic_bp,diastolic_bp,smoking,drinking,exercise,stress_level,family_history_diabetes,family_history_heart,family_history_obesity
0,18,F,22.0,120,80,Never,Never,Light,5,0,0,0

In [ ]:
BINARY     = ['family_history_diabetes', 'family_history_heart', 'family_history_obesity']

CONTINUOUS = [
    'age',
    'bmi',
    'systolic_bp',
    'diastolic_bp',
    'stress_level'
]

CATEGORICAL = {
    'gender':   ['Male', 'Female', 'Other'],
    'smoking':  ['Never', 'Former', 'Current'],
    'drinking': ['Never', 'Occasional', 'Regular', 'Heavy'],
    'exercise': ['Sedentary', 'Light', 'Moderate', 'Intense'],
}

cont_vals = pd.DataFrame(
    scaler.transform(df[CONTINUOUS]),
    columns=CONTINUOUS, index=df.index
)

cat_dfs = []
for col, categories in CATEGORICAL.items():
    for cat in categories:
        cat_dfs.append(pd.Series(
            (df[col] == cat).astype(int),
            name=f"{col}_{cat}", index=df.index
        ))
cat_vals = pd.concat(cat_dfs, axis=1)

bin_vals = df[BINARY].reset_index(drop=True)
cont_vals = cont_val.reset_index(drop=True)
cat_vals = cat_vals.reset_index(drop=True)

transformed_input = pd.concat(cont_vals, cat_vals, bin_vals , axis=1)